---
  notifications:
    email: false

  matrix:
    include:
      - language: go
        go: 1.6.x
        env: TESTFILE=unit.sh
      - language: go
        go: 1.7.x
        env: TESTFILE=unit.sh
      - language: go
        go: master
        env: TESTFILE=unit.sh
      - language: generic
        sudo: required
        services:
          - docker
        env: TESTFILE=integration.sh

  script:
    - ./.travis/$TESTFILE